name: Run AnghaBench CI Cron Jobs

on:
  # Run this workflow every day at 3am
  schedule:
   - cron: "0 3 * * *"

jobs:
  AnghaBenchRuns:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        llvm: ["11"]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    # https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Small Run (1K) against LLVM ${{ matrix.llvm }}
      run: |
        libraries/lifting-tools-ci/cloud/run-do-droplet.py --name "Anvill CI 1K Run" --script scripts/run-on-anghabench.sh --env-vars RUN_SIZE=1k,ANVILL_BRANCH=${BRANCH},LLVM_VERSION=${{ matrix.llvm }}
      env:
        SLACK_HOOK: ${{ secrets.SLACK_HOOK }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DO_TOKEN: ${{ secrets.DO_TOKEN }}
        BINJA_DECODE_KEY: ${{ secrets.BINJA_DECODE_KEY }}
        BRANCH: ${{ steps.extract_branch.outputs.branch }}
    #- name: Big Run (1M) against LLM ${{ matrix.llvm }}
    #  run: |
    #    libraries/lifting-tools-ci/cloud/run-do-droplet.py --name "Anvill CI 1M Run" --script scripts/run-on-anghabench.sh --env-vars RUN_SIZE=1m,ANVILL_BRANCH=${BRANCH},LLVM_VERSION=${{ matrix.llvm }}
    #  env:
    #    SLACK_HOOK: ${{ secrets.SLACK_HOOK }}
    #    DO_TOKEN: ${{ secrets.DO_TOKEN }}
    #    BINJA_DECODE_KEY: ${{ secrets.BINJA_DECODE_KEY }}
    #    BRANCH: ${{ steps.extract_branch.outputs.branch }}
 
 
